Processing data in models
fed1k/Rails-Blog-App pull request #2
Opened 2022-07-07 20:45 UTC by fed1k

## Create models
* Create model classes for all entities as shown in the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).
* Set up associations between models.
## Use models to insert data
* Familiarize yourself with ['rails c' command](https://guides.rubyonrails.org/command_line.html#bin-rails-console).
* Open rails console for your project.
* Create at least one user by running the following code:
```
first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
```
* Create at least 4 posts written by one of the users you created by running the following code:
     `first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')`
* Create at least 6 posts comments for one of the posts you created by running the following code:
     `Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )`
* Use other [CRUD methods](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/active_record_crud.md) to find, update and delete entities.
## Create custom methods
Your models should include some additional methods.

* Users
  * A method that returns the 3 most recent posts for a given user.
* Posts
  * A method that updates the posts counter for a user.
  * A method which returns the 5 most recent comments for a given post.
* Comments
  * A method that updates the comments counter for a post.
* Likes
  * A method that updates the likes counter for a post.
* Go to `rails c` and check if your methods are working.

# Happy Reviewing🐱‍👤

2022-07-07 23:47 UTC, mahbubul14 requested changes
Hi @fed1k ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ]  Currently, your `README` file is not descriptive enough. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

- [ ] Kindly check the inline comments under the review. :arrow_down: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-07 23:47 UTC, mahbubul14 commented on app/models/user.rb
> +
- [x] You should use those lines of code on the rails console to check if your methods are working or not. It shouldn't be here.

2022-07-07 23:47 UTC, mahbubul14 commented on app/models/post.rb
> +    User.save
- [ ] Optional: You can use `author.increment!(:post_counter)` instead of `User.posts_counter += 1` :+1:

2022-07-07 23:47 UTC, mahbubul14 commented on app/models/like.rb
> +    Post.likes_counter += 1
- [ ] Optional: You can use `post.increment!(:likes_counter)` instead of `Post.likes_counter += 1` :+1:

2022-07-07 23:47 UTC, mahbubul14 commented on app/models/comment.rb
> +    Post.comments_counter += 1
- [ ] Optional: You can use `post.increment!(:comments_counter)` instead of `Post.comments_counter += 1` :+1:

2022-07-08 00:34 UTC, andersonlebon approved these changes
## Hi @fed1k 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-08 00:34 UTC, merged